"""Regenerate docs/RULES.md from the YAML files in rules/.   Usage: python scripts/gen_rules_doc.py"""
from itertools import groupby
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ORDER = ["critical", "high", "medium", "low", "informational"]


def pretty_tag(tag: str) -> str:
    tag = tag.removeprefix("attack.")
    return tag.upper() if tag.startswith("t1") else tag.replace("_", " ")


def load() -> list[dict]:
    rows = []
    for f in sorted((ROOT / "rules").rglob("*.yml")):
        for doc in yaml.safe_load_all(f.read_text(encoding="utf-8")):
            if doc:
                rows.append({"group": f.parent.name, "name": doc["name"], "level": doc.get("level", "medium"),
                             "kind": doc["correlation"]["type"] if "correlation" in doc else "rule",
                             "tags": [pretty_tag(t) for t in doc.get("tags", [])],
                             "desc": " ".join(str(doc.get("description", "")).split()),
                             "fps": doc.get("falsepositives", [])})
    return sorted(rows, key=lambda r: (r["group"], ORDER.index(r["level"]), r["name"]))


def main() -> None:
    rows = load()
    out = ["# Rule catalogue", "",
           "Generated by `scripts/gen_rules_doc.py`. Rules with level *informational* are building blocks: "
           "they never alert on their own, correlation rules build on them.", ""]
    for group, items in groupby(rows, key=lambda r: r["group"]):
        out += [f"## {group}", "", "| Rule | Level | Type | ATT&CK / tactic | What it detects | Known false positives |",
                "|---|---|---|---|---|---|"]
        for r in items:
            out.append(f"| `{r['name']}` | {r['level']} | {r['kind']} | {', '.join(r['tags']) or '-'} | "
                       f"{r['desc']} | {'; '.join(r['fps']) or '-'} |")
        out.append("")
    (ROOT / "docs" / "RULES.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote docs/RULES.md ({len(rows)} rules)")


if __name__ == "__main__":
    main()
